import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Header } from '../components/Header';
import VideoCarousel from '../components/VideoCarousel';

const Home: NextPage = () => {
  return (
    <>
    <Header />

    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <VideoCarousel videos={[1,2,3,4,5,8,9]}/>
      </main>

      <footer className={styles.footer}>
        <h3>Video Share</h3>
      </footer>
    </div>
    </>
  );
};

export default Home;
